### ISSUE TITLE
Document what the "*" means in "MIT*" and "BSD*"

### ISSUE THREAD

**Issue by HendrikW** [pivotal-legacy/LicenseFinder#460]
I have the issue that I have no idea what this is trying to tell me :-) , the semantics of this seem to be missing in the documentation, at least I would have expected them there.

**Comment by kdykeman** [comment]
Hi @HendrikW,

Can describe which package manager(s) is/are applicable for your project and which dependencies you're seeing the "*" at the end?

I think the behavior may be more a bug rather than intentional behavior, so any additional information would help. So far, I've only been able to reproduce this for projects using yarn and npm package managers.

**Comment by halostatue** [comment]
@kdykeman I have seen this for some NPM/yarn packages (vue-form-wizard is one).

**Comment by FrederikNS** [comment]
I'm also seeing this for a few ruby gems:
```
async-foreach, 0.1.3, MIT*
cyclist, 0.2.2, MIT*
indexof, 0.0.1, MIT*
pleeease-filters, 4.0.0, MIT*

**Comment by HendrikW** [comment]
yes, I had exactly the case with ruby gems mentioned above – sorry for the late reply

**Comment by kdykeman** [comment]
It looks like this is actually coming from yarn. When a node_module's `package.json` doesn't explicitly declare a license, yarn indicates that it has inferred the license based on some keywords in other files by [appending an asterisk to the license name](https://github.com/yarnpkg/yarn/blob/1711e72d7d86af26a4ea4cfbb9608c47989fb913/src/util/normalize-manifest/infer-license.js#L28-L35).

Beyond documenting this, it should be made clear whether this behavior is intentional.

**Comment by kdykeman** [comment]
The [Output from `report`](https://github.com/pivotal-legacy/LicenseFinder/blob/master/README.md#output-from-report) section of `README.md` has been updated with a note describing why the asterisk appears.
